---
--- Generated by Luanalysis
--- Created by DingYvMing.
--- DateTime: 2026/2/6 10:24
---
--获取锁中的线程id
local id=redis.call("get",KEYS[1])
--比较线程标识与锁中的标识是否一致
if(id == ARGV[1]) then
    --删除锁
    redis.call("del",KEYS[1])
end
return 0